### ISSUE TITLE
Many pages in admin interface have no content (blank, white) when in edit mode.

### ISSUE THREAD

**Issue by darkos** [lektor/lektor-website#162]
### Many pages in admin interface have no content (blank, white) when in edit mode.
For example:
* http://localhost:5000/ - everything seems OK
* http://localhost:5000/admin/root/edit - just meny on the left side. No fields for the page content
** and javascript errors in Chrome developer console
* by pressing on the "Preview" button in left many, page looks ok in preview
** and javascript errors in Chrome developer console
* by pressing on "Edit" button on the left, nothing happens until i press the "eye" icon
** and **NO** javascript errors in Chrome developer console after that
### Reproducing

I started lektor server inside lektor-website (venv activated)
Web site looks great.
After switced to admin (http://localhost:5000/admin/root/edit), nothing in admin, so i looked the page source and found:
`<!doctype html>`
  `<title>Lektor Admin</title>`
  `<link rel=stylesheet type=text/css href="/admin/static/gen/styles.css">`
   `<div id=dash>`
  `<div class=loadbox>`
  `<p>Loading Interface ...</p>`
  `<noscript>You must enable JavaScript to use the editing interface.</noscript>`
  `</div>`
  `</div>`
  `<script type=text/javascript>`
  `var $LEKTOR_CONFIG = {`
  `admin_root: "/admin",`
  `site_root: "",`
  `lang: "en"`
  `};`
  `</script>`  
  `<script type=text/javascript src="/admin/static/gen/vendor.js"></script>`
  `<script type=text/javascript src="/admin/static/gen/app.js"></script>`
* Tried in Chrome and Firefox and result was the same
* The same applies for any page
* My personal Lektor projects look OK (i used teh same, MASTER branch of lektor built locally)

Ubuntu 16
Python 2.7.13
node: v4.2.6
npm: 3.5.2

* I cloned this: https://github.com/lektor/lektor-website
* I did all this:
`$ git clone https://github.com/lektor/lektor`
`$ cd lektor`
`$ virtualenv venv`
`$ . venv/bin/activate`
`$ pip install --editable .`
`$ make build-js`
`$ make install-git-hooks`
`$ export LEKTOR_DEV=1`

**Comment by nixjdm** [comment]
@darkos I'm pretty sure you stumbled upon https://github.com/lektor/lektor/issues/390. There is a bugfix pull request up for this issue right now here: https://github.com/lektor/lektor/pull/427.

If you open your JS console on http://localhost:5000/admin/root/edit you may confirm that it's the same as my 'how to reproduce' report in my most recent comment on the pull request. If you happen to know your way around ES6, I'd appreciate feedback on that pull request.

**Comment by darkos** [comment]
This is what I got
```javascript
Uncaught (in promise) TypeError: Cannot read property 'props' of undefined
    at Object.renderFormField (eval at <anonymous> (app.js:658), <anonymous>:262:30)
    at Array.map (<anonymous>)
    at eval (eval at <anonymous> (app.js:628), <anonymous>:247:11)
    at Array.forEach (<anonymous>)
    at Object.renderFieldRows (eval at <anonymous> (app.js:628), <anonymous>:239:8)
    at eval (eval at <anonymous> (app.js:658), <anonymous>:287:28)
    at Array.map (<anonymous>)
    at Object.renderBlocks (eval at <anonymous> (app.js:658), <anonymous>:281:29)
    at Object.render (eval at <anonymous> (app.js:658), <anonymous>:382:12)
    at eval (eval at <anonymous> (vendor.js:889), <anonymous>:795:21)
```
Which is very similar, but I guess caused by the same issue
```javascript
Uncaught (in promise) TypeError: Cannot read property 'props' of undefined
    at Object.isActive (http://localhost:5000/admin/static/gen/app.js:9182:27)
    at http://localhost:5000/admin/static/gen/app.js:9241:29
    at Array.map (native)
    at Object.render (http://localhost:5000/admin/static/gen/app.js:9232:44)
    at http://localhost:5000/admin/static/gen/vendor.js:16301:22
    at measureLifeCyclePerf (http://localhost:5000/admin/static/gen/vendor.js:15581:13)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:5000/admin/static/gen/vendor.js:16300:26)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:5000/admin/static/gen/vendor.js:16327:33)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:5000/admin/static/gen/vendor.js:15867:31)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:5000/admin/static/gen/vendor.js:15763:22)
```

**Comment by nixjdm** [comment]
I think those errors didn't always trip in the same order each time, but yeah, that's the same root problem. I just merged the fix for it though. If you update to master, this should be gone. Please report back any further problems.

**Comment by darkos** [comment]
Works as you promised.
There are some warnings in console...
Warning: [react-router]...
But i have a feeling that these are known problems.
Thank you very much for fixing this.
